services:

  mongo:
    image: mongo:8
    container_name: learnstack-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  api:
    image: learnstack-api

    container_name: learnstack-api

    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile

    depends_on:
      - mongo

    ports:
      - "4000:4000"

    env_file:
      - apps/api/.env.docker

  web:
    image: learnstack-web

    container_name: learnstack-web
    
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile

    depends_on:
      - api

    ports:
      - "3000:3000"

    env_file:
      - apps/web/.env.docker

volumes:
  mongo_data: